// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOAN93rKAzPqfrhOmVvR_f1QJ8UMqc3h8',
    appId: '1:1081236574630:web:34fad2787a2cc5150cbf67',
    messagingSenderId: '1081236574630',
    projectId: 'spotify-kamal',
    authDomain: 'spotify-kamal.firebaseapp.com',
    storageBucket: 'spotify-kamal.appspot.com',
    measurementId: 'G-0HYE6KCX6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQsy6CEf_GmMIWD3HmmI8RcpYOC2JHf2U',
    appId: '1:1081236574630:android:ecdf8c9544c802200cbf67',
    messagingSenderId: '1081236574630',
    projectId: 'spotify-kamal',
    storageBucket: 'spotify-kamal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Nc9EReBzlQjXSM2cG27rvXKFYRfPMdU',
    appId: '1:1081236574630:ios:af7ff64c3b9f68b50cbf67',
    messagingSenderId: '1081236574630',
    projectId: 'spotify-kamal',
    storageBucket: 'spotify-kamal.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Nc9EReBzlQjXSM2cG27rvXKFYRfPMdU',
    appId: '1:1081236574630:ios:af7ff64c3b9f68b50cbf67',
    messagingSenderId: '1081236574630',
    projectId: 'spotify-kamal',
    storageBucket: 'spotify-kamal.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOAN93rKAzPqfrhOmVvR_f1QJ8UMqc3h8',
    appId: '1:1081236574630:web:e69c3e688d1e3c4e0cbf67',
    messagingSenderId: '1081236574630',
    projectId: 'spotify-kamal',
    authDomain: 'spotify-kamal.firebaseapp.com',
    storageBucket: 'spotify-kamal.appspot.com',
    measurementId: 'G-C3MR93TREP',
  );
}
